"use client";
import HeaderLanding from "@/components/HeaderLanding/HeaderLanding";
import "./globals.css";
import FooterLanding from "@/components/FooterLanding/FooterLanding";
import { useState, useEffect } from "react";
import Loader from "@/components/common/Loader";

export const metadata = {
  title: "SI UMKM",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div>
          {loading ? (
            <Loader />
          ) : (
            <div>
              <HeaderLanding />
              <main>{children}</main>
              <FooterLanding />
            </div>
          )}
        </div>
      </body>
    </html>
  );
}
